# Generated by Django 5.2.9 on 2025-12-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="events_even_type_re_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_even_date_de_e71099_idx",
            old_name="events_even_date_de_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_even_date_fi_41a9bd_idx",
            old_name="events_even_date_fi_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_even_createu_47604a_idx",
            old_name="events_even_createu_idx",
        ),
        migrations.RenameIndex(
            model_name="event",
            new_name="events_even_date_de_0f2037_idx",
            old_name="events_even_date_de_date_fi_idx",
        ),
        migrations.RenameIndex(
            model_name="eventfile",
            new_name="events_even_event_i_48feeb_idx",
            old_name="events_even_event_id_ordre_idx",
        ),
        migrations.RenameIndex(
            model_name="eventfile",
            new_name="events_even_type_fi_c1adb2_idx",
            old_name="events_even_type_fi_idx",
        ),
        migrations.RemoveField(
            model_name="event",
            name="date_fin_recurrence",
        ),
        migrations.RemoveField(
            model_name="event",
            name="jours_recurrence",
        ),
        migrations.RemoveField(
            model_name="event",
            name="occurrences",
        ),
        migrations.RemoveField(
            model_name="event",
            name="type_recurrence",
        ),
        migrations.AddField(
            model_name="event",
            name="date_publication_avant_le",
            field=models.DateField(
                blank=True,
                help_text="Date avant laquelle l'événement doit être publié sur les réseaux sociaux (information pour la communication)",
                null=True,
                verbose_name="date de publication avant le",
            ),
        ),
    ]
