# Generated by Django 5.2.9 on 2026-01-06 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_remove_event_events_even_type_re_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="commentaire_validation_dga",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaire validation DGA"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="commentaire_validation_dgs",
            field=models.TextField(
                blank=True, null=True, verbose_name="commentaire validation DGS"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="date_validation_dga",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date validation DGA"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="date_validation_dgs",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="date validation DGS"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="demande_validation_dga",
            field=models.BooleanField(
                default=False,
                help_text="Demander une validation au DGA",
                verbose_name="demande validation DGA",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="demande_validation_dgs",
            field=models.BooleanField(
                default=False,
                help_text="Demander une validation au DGS",
                verbose_name="demande validation DGS",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="statut_validation_dga",
            field=models.CharField(
                choices=[
                    ("non_demande", "Non demandé"),
                    ("en_attente", "En attente"),
                    ("valide", "Validé"),
                    ("refuse", "Refusé"),
                ],
                db_index=True,
                default="non_demande",
                max_length=20,
                verbose_name="statut validation DGA",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="statut_validation_dgs",
            field=models.CharField(
                choices=[
                    ("non_demande", "Non demandé"),
                    ("en_attente", "En attente"),
                    ("valide", "Validé"),
                    ("refuse", "Refusé"),
                ],
                db_index=True,
                default="non_demande",
                max_length=20,
                verbose_name="statut validation DGS",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="validateur_dga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validations_dga",
                to=settings.AUTH_USER_MODEL,
                verbose_name="validateur DGA",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="validateur_dgs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validations_dgs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="validateur DGS",
            ),
        ),
    ]
