# Generated by Django 5.2.9 on 2026-01-06 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_add_validation_fields"),
        (
            "secteurs",
            "0003_rename_secteurs_se_nom_idx_secteurs_se_nom_c375e0_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["statut_validation_dga", "statut_validation_dgs"],
                name="events_even_statut__500a2c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["createur", "date_debut"], name="events_even_createu_53d269_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["date_debut", "statut_validation_dga"],
                name="events_even_date_de_dd84c9_idx",
            ),
        ),
    ]
