# Generated by Django 5.2.9 on 2025-12-30 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("secteurs", "0002_populate_initial_secteurs"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="secteur",
            new_name="secteurs_se_nom_c375e0_idx",
            old_name="secteurs_se_nom_idx",
        ),
        migrations.RenameIndex(
            model_name="secteur",
            new_name="secteurs_se_ordre_d9b1bc_idx",
            old_name="secteurs_se_ordre_idx",
        ),
        migrations.RenameIndex(
            model_name="secteur",
            new_name="secteurs_se_created_e5c93a_idx",
            old_name="secteurs_se_created_idx",
        ),
    ]
