# Generated by Django 5.2.9 on 2025-12-29 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Adresse email utilisée comme identifiant unique",
                        max_length=254,
                        unique=True,
                        verbose_name="adresse email",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=150, verbose_name="prénom"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, db_index=True, max_length=150, verbose_name="nom"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Désigne si cet utilisateur doit être traité comme actif. Désélectionnez ceci au lieu de supprimer le compte.",
                        verbose_name="actif",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Désigne si l'utilisateur peut se connecter à ce site admin.",
                        verbose_name="membre du staff",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="date d'inscription",
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Désigne si l'email de l'utilisateur a été vérifié.",
                        verbose_name="email vérifié",
                    ),
                ),
                (
                    "email_verification_token",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="token de vérification email",
                    ),
                ),
                (
                    "email_verification_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="date d'envoi du token de vérification",
                    ),
                ),
                (
                    "password_reset_token",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="token de réinitialisation de mot de passe",
                    ),
                ),
                (
                    "password_reset_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="date d'envoi du token de réinitialisation",
                    ),
                ),
                (
                    "notify_welcome_email",
                    models.BooleanField(
                        default=True,
                        help_text="Recevoir un email de bienvenue lors de l'inscription",
                        verbose_name="notifier email de bienvenue",
                    ),
                ),
                (
                    "notify_password_change",
                    models.BooleanField(
                        default=True,
                        help_text="Recevoir un email lors du changement de mot de passe",
                        verbose_name="notifier changement de mot de passe",
                    ),
                ),
                (
                    "notify_new_login",
                    models.BooleanField(
                        default=True,
                        help_text="Recevoir un email lors d'une nouvelle connexion",
                        verbose_name="notifier nouvelle connexion",
                    ),
                ),
                (
                    "notify_security_alerts",
                    models.BooleanField(
                        default=True,
                        help_text="Recevoir des emails pour les alertes de sécurité (nouvelle connexion depuis un nouvel appareil, etc.)",
                        verbose_name="notifier alertes de sécurité",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
                "ordering": ["-date_joined"],
                "indexes": [
                    models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
                    models.Index(
                        fields=["is_active", "email_verified"],
                        name="accounts_us_is_acti_83e0ef_idx",
                    ),
                    models.Index(
                        fields=["-date_joined"], name="accounts_us_date_jo_bab293_idx"
                    ),
                ],
            },
        ),
    ]
