# Generated by Django 5.2.9 on 2025-12-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="token de vérification email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name="token de réinitialisation de mot de passe",
            ),
        ),
    ]
