# Generated by Django 5.2.9 on 2025-12-30 14:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("role", "0002_populate_initial_roles"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="role",
            new_name="role_role_nom_ac3988_idx",
            old_name="role_role_nom_idx",
        ),
        migrations.RenameIndex(
            model_name="role",
            new_name="role_role_niveau_a403b1_idx",
            old_name="role_role_niveau_idx",
        ),
        migrations.RenameIndex(
            model_name="role",
            new_name="role_role_created_e684fb_idx",
            old_name="role_role_created_idx",
        ),
    ]
