# Generated by Django 5.2.9 on 2026-01-05 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fractionnement", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="periodeconge",
            index=models.Index(
                fields=["user", "annee_civile", "type_conge"],
                name="fractionnem_user_id_94c163_idx",
            ),
        ),
    ]
