# Generated by Django 5.2.9 on 2026-01-06 08:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fractionnement", "0004_periodeconge_fractionnem_user_id_94c163_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="calculfractionnement",
            new_name="fractionnem_user_id_d91ed8_idx",
            old_name="fractionnem_calc_user_annee_idx",
        ),
        migrations.RenameIndex(
            model_name="calculfractionnement",
            new_name="fractionnem_annee_87aa68_idx",
            old_name="fractionnem_calc_annee_idx",
        ),
        migrations.RenameIndex(
            model_name="cyclehebdomadaire",
            new_name="fractionnem_user_id_09b296_idx",
            old_name="fractionnem_cycle_user_annee_idx",
        ),
        migrations.RenameIndex(
            model_name="cyclehebdomadaire",
            new_name="fractionnem_annee_c9aab0_idx",
            old_name="fractionnem_cycle_annee_idx",
        ),
        migrations.RenameIndex(
            model_name="parametresannee",
            new_name="fractionnem_user_id_2913bd_idx",
            old_name="fractionnem_param_user_annee_idx",
        ),
        migrations.RenameIndex(
            model_name="periodeconge",
            new_name="fractionnem_user_id_7eecc6_idx",
            old_name="fractionnem_periode_user_annee_idx",
        ),
        migrations.RenameIndex(
            model_name="periodeconge",
            new_name="fractionnem_date_de_83ebe1_idx",
            old_name="fractionnem_periode_dates_idx",
        ),
        migrations.RenameIndex(
            model_name="periodeconge",
            new_name="fractionnem_user_id_49c891_idx",
            old_name="fractionnem_periode_user_date_idx",
        ),
        migrations.AddField(
            model_name="periodeconge",
            name="debut_type",
            field=models.CharField(
                choices=[("matin", "Matin"), ("apres_midi", "Après-midi")],
                default="matin",
                help_text="La période commence le matin ou l'après-midi",
                max_length=10,
                verbose_name="début de période",
            ),
        ),
        migrations.AddField(
            model_name="periodeconge",
            name="fin_type",
            field=models.CharField(
                choices=[("matin", "Matin"), ("apres_midi", "Après-midi")],
                default="apres_midi",
                help_text="La période finit le matin ou l'après-midi",
                max_length=10,
                verbose_name="fin de période",
            ),
        ),
        migrations.AlterField(
            model_name="cyclehebdomadaire",
            name="jours_ouvres_ou_ouvrables",
            field=models.CharField(
                choices=[
                    ("ouvres", "Jours ouvrés (lundi-vendredi)"),
                    ("ouvrables", "Jours ouvrables (lundi-samedi)"),
                ],
                default="ouvres",
                help_text="Type de jours utilisés pour le calcul",
                max_length=10,
                verbose_name="jours ouvrés ou ouvrables",
            ),
        ),
        migrations.AlterField(
            model_name="parametresannee",
            name="jours_ouvres_ou_ouvrables",
            field=models.CharField(
                choices=[
                    ("ouvres", "Jours ouvrés (lundi-vendredi)"),
                    ("ouvrables", "Jours ouvrables (lundi-samedi)"),
                ],
                default="ouvres",
                help_text="Type de jours utilisés pour les calculs de l'année",
                max_length=10,
                verbose_name="jours ouvrés ou ouvrables",
            ),
        ),
        migrations.AlterField(
            model_name="periodeconge",
            name="nb_jours",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("0.0"),
                help_text="Nombre de jours calculés automatiquement (peut être décimal)",
                max_digits=4,
                verbose_name="nombre de jours",
            ),
        ),
        migrations.AddIndex(
            model_name="periodeconge",
            index=models.Index(
                fields=["type_conge"], name="fractionnem_type_co_82425d_idx"
            ),
        ),
    ]
